id: P006843
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:26:09.815701
source_metadata:
  id: bdr:W23917
  title: ཤངས་པ་བཀའ་བརྒྱུད་པའི་ཁྲིད་སྐོར་ཐང་རྒྱལ་ལུགས
  author: ''
  volumes:
    e5cad60cb386406d80047706c9852821:
      image_group_id: I3516
      title: ''
      volume_number: 1
      total_pages: 520
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
